spring:
  application:
    name: priority-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://queueshield-postgres:5432/priority_db}
    username: ${DB_USERNAME:queueshield}
    password: ${DB_PASSWORD:queueshield}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    open-in-view: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: ${REDIS_HOST:queueshield-redis}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >-
          incidentPrioritizedEvent:com.queueshield.priorityservice.event.IncidentPrioritizedEvent
    consumer:
      group-id: priority-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.queueshield.priorityservice.event
        spring.json.type.mapping: >-
          incidentEvent:com.queueshield.priorityservice.event.IncidentEvent
        spring.json.value.default.type: com.queueshield.priorityservice.event.IncidentEvent

resource-service:
  base-url: ${RESOURCE_SERVICE_URL:http://resource-service:8085}

server:
  port: ${SERVER_PORT:8084}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.queueshield: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
