apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueshield-redis
  labels: {{- include "queueshield.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: queueshield-redis }
  template:
    metadata:
      labels: { app: queueshield-redis }
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          readinessProbe:
            exec: { command: ["redis-cli", "ping"] }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            exec: { command: ["redis-cli", "ping"] }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- .Values.resources.light | toYaml | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: queueshield-redis
  labels: {{- include "queueshield.labels" . | nindent 4 }}
spec:
  selector: { app: queueshield-redis }
  ports:
    - port: 6379
      targetPort: 6379
